name: Micks cool Action

on: [push]

jobs: 
  greeting:
      runs-on: ubuntu-latest

      steps:
        - name: Monkey business
          run: echo "🦧🦍🐒"

  log-checker: 
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code 👀
          uses: actions/checkout@v3

        - name: Looking for logs 🦫
          run: |
              echo "🦫🦫🦫 sending the log inspectors"
              count=$(grep -ro 'console\.log' . | wc -l)
              echo "🪵 Found $count occurrences of 'console.log'"
